MAX_ITERATION=10 node ../ex5/client/nodejs/udp/index.js
MAX_ITERATION=10 node ../ex5/client/nodejs/udp/index.js & SAVE_INFO=TRUE MAX_ITERATION=10 node ../ex5/client/nodejs/udp/index.js
MAX_ITERATION=10 node ../ex5/client/nodejs/udp/index.js & MAX_ITERATION=10 node ../ex5/client/nodejs/udp/index.js & MAX_ITERATION=10 node ../ex5/client/nodejs/udp/index.js & MAX_ITERATION=10 node ../ex5/client/nodejs/udp/index.js & SAVE_INFO=TRUE MAX_ITERATION=10 node ../ex5/client/nodejs/udp/index.js
MAX_ITERATION=10 node ../ex5/client/nodejs/udp/index.js & MAX_ITERATION=10 node ../ex5/client/nodejs/udp/index.js & MAX_ITERATION=10 node ../ex5/client/nodejs/udp/index.js & MAX_ITERATION=10 node ../ex5/client/nodejs/udp/index.js & MAX_ITERATION=10 node ../ex5/client/nodejs/udp/index.js & MAX_ITERATION=10 node ../ex5/client/nodejs/udp/index.js & MAX_ITERATION=10 node ../ex5/client/nodejs/udp/index.js & MAX_ITERATION=10 node ../ex5/client/nodejs/udp/index.js & MAX_ITERATION=10 node ../ex5/client/nodejs/udp/index.js & SAVE_INFO=TRUE MAX_ITERATION=10 node ../ex5/client/nodejs/udp/index.js
MAX_ITERATION=10 node ../ex5/client/nodejs/tcp/index.js
MAX_ITERATION=10 node ../ex5/client/nodejs/tcp/index.js & SAVE_INFO=TRUE MAX_ITERATION=10 node ../ex5/client/nodejs/tcp/index.js
MAX_ITERATION=10 node ../ex5/client/nodejs/tcp/index.js & MAX_ITERATION=10 node ../ex5/client/nodejs/tcp/index.js & MAX_ITERATION=10 node ../ex5/client/nodejs/tcp/index.js & MAX_ITERATION=10 node ../ex5/client/nodejs/tcp/index.js & SAVE_INFO=TRUE MAX_ITERATION=10 node ../ex5/client/nodejs/tcp/index.js
MAX_ITERATION=10 node ../ex5/client/nodejs/tcp/index.js & MAX_ITERATION=10 node ../ex5/client/nodejs/tcp/index.js & MAX_ITERATION=10 node ../ex5/client/nodejs/tcp/index.js & MAX_ITERATION=10 node ../ex5/client/nodejs/tcp/index.js & MAX_ITERATION=10 node ../ex5/client/nodejs/tcp/index.js & MAX_ITERATION=10 node ../ex5/client/nodejs/tcp/index.js & MAX_ITERATION=10 node ../ex5/client/nodejs/tcp/index.js & MAX_ITERATION=10 node ../ex5/client/nodejs/tcp/index.js & MAX_ITERATION=10 node ../ex5/client/nodejs/tcp/index.js & SAVE_INFO=TRUE MAX_ITERATION=10 node ../ex5/client/nodejs/tcp/index.js
MAX_ITERATION=10 node ../ex6/client/index.js
MAX_ITERATION=10 node ../ex6/client/index.js & SAVE_INFO=TRUE MAX_ITERATION=10 node ../ex6/client/index.js
MAX_ITERATION=10 node ../ex6/client/index.js & MAX_ITERATION=10 node ../ex6/client/index.js & MAX_ITERATION=10 node ../ex6/client/index.js & MAX_ITERATION=10 node ../ex6/client/index.js & SAVE_INFO=TRUE MAX_ITERATION=10 node ../ex6/client/index.js
MAX_ITERATION=10 node ../ex6/client/index.js & MAX_ITERATION=10 node ../ex6/client/index.js & MAX_ITERATION=10 node ../ex6/client/index.js & MAX_ITERATION=10 node ../ex6/client/index.js & MAX_ITERATION=10 node ../ex6/client/index.js & MAX_ITERATION=10 node ../ex6/client/index.js & MAX_ITERATION=10 node ../ex6/client/index.js & MAX_ITERATION=10 node ../ex6/client/index.js & MAX_ITERATION=10 node ../ex6/client/index.js & SAVE_INFO=TRUE MAX_ITERATION=10 node ../ex6/client/index.js
MAX_ITERATION=10 node ../ex5/client/nodejs/udp/index.js
MAX_ITERATION=10 node ../ex5/client/nodejs/udp/index.js & SAVE_INFO=TRUE MAX_ITERATION=10 node ../ex5/client/nodejs/udp/index.js
MAX_ITERATION=10 node ../ex5/client/nodejs/udp/index.js & MAX_ITERATION=10 node ../ex5/client/nodejs/udp/index.js & MAX_ITERATION=10 node ../ex5/client/nodejs/udp/index.js & MAX_ITERATION=10 node ../ex5/client/nodejs/udp/index.js & SAVE_INFO=TRUE MAX_ITERATION=10 node ../ex5/client/nodejs/udp/index.js
MAX_ITERATION=10 node ../ex5/client/nodejs/udp/index.js & MAX_ITERATION=10 node ../ex5/client/nodejs/udp/index.js & MAX_ITERATION=10 node ../ex5/client/nodejs/udp/index.js & MAX_ITERATION=10 node ../ex5/client/nodejs/udp/index.js & MAX_ITERATION=10 node ../ex5/client/nodejs/udp/index.js & MAX_ITERATION=10 node ../ex5/client/nodejs/udp/index.js & MAX_ITERATION=10 node ../ex5/client/nodejs/udp/index.js & MAX_ITERATION=10 node ../ex5/client/nodejs/udp/index.js & MAX_ITERATION=10 node ../ex5/client/nodejs/udp/index.js & SAVE_INFO=TRUE MAX_ITERATION=10 node ../ex5/client/nodejs/udp/index.js
MAX_ITERATION=10 node ../ex5/client/nodejs/tcp/index.js
MAX_ITERATION=10 node ../ex5/client/nodejs/tcp/index.js & SAVE_INFO=TRUE MAX_ITERATION=10 node ../ex5/client/nodejs/tcp/index.js
MAX_ITERATION=10 node ../ex5/client/nodejs/tcp/index.js & MAX_ITERATION=10 node ../ex5/client/nodejs/tcp/index.js & MAX_ITERATION=10 node ../ex5/client/nodejs/tcp/index.js & MAX_ITERATION=10 node ../ex5/client/nodejs/tcp/index.js & SAVE_INFO=TRUE MAX_ITERATION=10 node ../ex5/client/nodejs/tcp/index.js
MAX_ITERATION=10 node ../ex5/client/nodejs/tcp/index.js & MAX_ITERATION=10 node ../ex5/client/nodejs/tcp/index.js & MAX_ITERATION=10 node ../ex5/client/nodejs/tcp/index.js & MAX_ITERATION=10 node ../ex5/client/nodejs/tcp/index.js & MAX_ITERATION=10 node ../ex5/client/nodejs/tcp/index.js & MAX_ITERATION=10 node ../ex5/client/nodejs/tcp/index.js & MAX_ITERATION=10 node ../ex5/client/nodejs/tcp/index.js & MAX_ITERATION=10 node ../ex5/client/nodejs/tcp/index.js & MAX_ITERATION=10 node ../ex5/client/nodejs/tcp/index.js & SAVE_INFO=TRUE MAX_ITERATION=10 node ../ex5/client/nodejs/tcp/index.js
MAX_ITERATION=10 node ../ex6/client/index.js
MAX_ITERATION=10 node ../ex6/client/index.js & SAVE_INFO=TRUE MAX_ITERATION=10 node ../ex6/client/index.js
MAX_ITERATION=10 node ../ex6/client/index.js & MAX_ITERATION=10 node ../ex6/client/index.js & MAX_ITERATION=10 node ../ex6/client/index.js & MAX_ITERATION=10 node ../ex6/client/index.js & SAVE_INFO=TRUE MAX_ITERATION=10 node ../ex6/client/index.js
MAX_ITERATION=10 node ../ex6/client/index.js & MAX_ITERATION=10 node ../ex6/client/index.js & MAX_ITERATION=10 node ../ex6/client/index.js & MAX_ITERATION=10 node ../ex6/client/index.js & MAX_ITERATION=10 node ../ex6/client/index.js & MAX_ITERATION=10 node ../ex6/client/index.js & MAX_ITERATION=10 node ../ex6/client/index.js & MAX_ITERATION=10 node ../ex6/client/index.js & MAX_ITERATION=10 node ../ex6/client/index.js & SAVE_INFO=TRUE MAX_ITERATION=10 node ../ex6/client/index.js
